spring:
  profiles:
    active: ${APP_PROFILES:prod}

  datasource:
    url:      ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${OAUTH2_ISSUER}
          audiences:  ${OAUTH2_AUDIENCE}

logging:
  level:
    org.springframework.messaging: TRACE
    org.springframework.web: TRACE

app:
  auth-server:
    access-token: ${OAUTH2_ACCESS_TOKEN}
    url: ${OAUTH2_ISSUER}
    userinfo-endpoint: ${OAUTH2_USERINFO_ENDPOINT}
