spring:
  datasource:
    url:      ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}

  security:
    oauth2:
      resourceserver:
        userinfo-endpoint: ${OAUTH2_USERINFO_ENDPOINT}
        jwt:
          issuer-uri: ${OAUTH2_ISSUER_URI}
          audiences:  ${OAUTH2_AUDIENCE}

app:
  auth-server:
    url: ${OAUTH2_ISSUER_URI}
    userinfo-endpoint: ${OAUTH2_USERINFO_ENDPOINT}